baseURL = "/"
title = "Tiago Moreira"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Tiago Moreira" # title for frontpage, may include image
copyright = "Tiago Moreira"
description = 'Game Developer - Programmer'
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = [""]

[[params.menu.main]]
url = '/'
title = "Home"


[[params.menu.main]]
url = '/projects/'
title = "Projects"


[[params.menu.main]]
url = '/resume/'
title = "Resumé"

[[params.menu.main]]
url = '/contact/'
title = "Contacts"


[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
body = '''
My interests are in programming for game development, AI behaviour and networking.
'''

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true


[[params.two.section]]
img = "img/ttored.jpg"
img_alt = "Thunder tier one image"
title = "TTO Mod Campaign Project" 
body = """
I am currently collaborating with a group of my fellow bachelor's students on a mod campaign for TTO. 
### [Check it out on Steam](https://steamcommunity.com/sharedfiles/filedetails/?id=3374103336).

My roles and contributions to the project:  
**Producer** | **Game Designer** | **Sound Designer** | **Main Programmer**
"""
[[params.two.section.link]]
href = "projects/thundertierone/"
text = "Project Details"
special = false


[[params.two.section]]
img = "img/vv.png"
title = 'Project Red - Virtual Campus'
body = """
- **Front End and Middleware Development:** Implemented the entire front end and middleware in React.
- **Translation of Functions:** Adapted bilateral JavaScript functions from React to C# for WebGL in Unity.
- **Core Functionalities:** Developed essential functionalities within the Unity environment.

Check the example work [Here](https://conteudos.red-de.lusoinfo.com/assets/activities/ACT.VisitasLote3/?modality=16&base_url=https://dr.red-de.lusoinfo.com/) or [Here](https://conteudos.red-de.lusoinfo.com/assets/activities/ACT.VisitasLote2/?modality=16&base_url=https://dr.red-de.lusoinfo.com/)
"""
[[params.two.section.link]]
href = "/projects/virtualcampus"
text = "Project Details"
special = false

[[params.two.section]] 
img = "img/INDIANAJOAO.png" 
title = 'Indiana João'
body = """
**Platform:** TIC-80

Indiana João is a game I developed with fellow students, featuring a unique control mechanism utilizing a Raspberry Pico and a microphone module. 
The project highlights the integration of the C/C++ SDK, Fourier Fast Transform, and the TinyUSB library to create innovative audio-based controls.  

## Check it out [here](https://tic80.com/play?cart=4145).


"""

[[params.two.section.link]]
href = "/projects/indianajoao"
text = "Project Details"
special = false

[params.three]
enable = true
title = 'My Skill Set for games'

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Tools"
body = "Unity Engine </br> Unreal Engine </br> Blender </br> Audacity"

[[params.three.feature]]
icon = "solid fa-code"
title = "Code Languages"
body = "C# C++ C </br> MySQL </br> JavaScript/TypeScript </br> Python </br> Bash"

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Fields i can work"
body = "Programming </br> DevOps </br> Game/Level Design </br> Sound Design </br> Animation </br> VFX"



[params.cta]
enable = true
title = "Thank you for visiting"

[[params.cta.link]]
href = "/contact/"
text = "Contacts"
special = true

[[params.cta.link]]
href = "/resume/"
text = "Resumé"
special = false


[params.social]
twitter = ""
mastodon = ""
github = "github.com/betadino"
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
